// Generated by CoffeeScript 1.7.1
(function() {
  window.AnimationAbstract = (function() {
    AnimationAbstract.prototype.type = 'abstract';

    function AnimationAbstract(from, to, options) {
      this.options = {
        callback: function() {
          return console.debug("" + this.type + " animation is done");
        }
      };
      this.objects = {
        from: from,
        to: to
      };
      $.extend(this.options, options);
      return this;
    }

    AnimationAbstract.prototype.forward = function() {
      this.direction = 'forward';
      return this;
    };

    AnimationAbstract.prototype.back = function() {
      this.direction = 'back';
      return this;
    };

    AnimationAbstract.prototype.run = function(callback) {
      if (callback == null) {
        callback = false;
      }
      window.Animation.isAnimate = true;
      return this["_" + this.direction]((function(_this) {
        return function() {
          window.Animation.isAnimate = false;
          if (callback) {
            return callback(_this.objects.to);
          }
        };
      })(this));
    };

    AnimationAbstract.prototype.resize = function(planes) {
      return this._resize(planes);
    };

    return AnimationAbstract;

  })();

  $(function() {
    return window.animationTypes = {};
  });

}).call(this);

//# sourceMappingURL=AnimationAbstract.map
