// Generated by CoffeeScript 1.7.1
(function() {
  var AnimationMenu,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  AnimationMenu = (function(_super) {
    __extends(AnimationMenu, _super);

    function AnimationMenu() {
      return AnimationMenu.__super__.constructor.apply(this, arguments);
    }

    AnimationMenu.prototype.type = 'menu';

    AnimationMenu.prototype.durations = {
      main: 1000
    };

    AnimationMenu.prototype._forward = function(callback) {
      window.Animation.isAnimate = false;
      return this.objects.from.animate({
        left: "+=100"
      }, {
        duration: this.durations.main,
        queue: false,
        complete: function() {
          return callback();
        }
      });
    };

    AnimationMenu.prototype._back = function(callback) {
      window.Animation.isAnimate = false;
      return this.objects.from.animate({
        left: "-=100"
      }, {
        duration: this.durations.main,
        queue: false,
        complete: function() {
          return callback();
        }
      });
    };

    return AnimationMenu;

  })(window.AnimationAbstract);

  $(function() {
    return window.animationTypes.menu = AnimationMenu;
  });

}).call(this);

//# sourceMappingURL=AnimationMenu.map
