// Generated by CoffeeScript 1.7.1
(function() {
  var AnimationFade,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  AnimationFade = (function(_super) {
    __extends(AnimationFade, _super);

    function AnimationFade() {
      return AnimationFade.__super__.constructor.apply(this, arguments);
    }

    AnimationFade.prototype.type = 'fade';

    AnimationFade.prototype.durations = {
      main: 2000
    };

    AnimationFade.prototype._forward = function(callback) {
      return this._base(callback);
    };

    AnimationFade.prototype._back = function(callback) {
      return this._base(callback);
    };

    AnimationFade.prototype._base = function(callback) {
      this._prepare();
      return this.objects.to.fadeIn(this.durations.main, callback);
    };

    AnimationFade.prototype._prepare = function() {
      return this.objects.to.css({
        left: 0,
        top: 0
      });
    };

    return AnimationFade;

  })(window.AnimationAbstract);

  $(function() {
    return window.animationTypes.fade = AnimationFade;
  });

}).call(this);

//# sourceMappingURL=AnimationFade.map
