// Generated by CoffeeScript 1.7.1
(function() {
  var Application;

  Application = (function() {
    function Application() {
      this.firstLoad = true;
      this.initMedia();
      this.initObjects();
      this.initSplash();
    }

    Application.prototype.initMedia = function() {
      return this.currentMedia = (function() {
        switch (parseInt($('body').css('z-index'))) {
          case 1:
            return 'normal';
          case 2:
            return 'small';
          case 3:
            return 'big';
          default:
            return 'normal';
        }
      })();
    };

    Application.prototype.initObjects = function() {
      this.article = new Article();
      this.navigation = new Navigation();
      this.menu = new Menu();
      this.scroll = new Scroll({
        isMaximum: (function(_this) {
          return function() {
            return $('.gotoNext').trigger('click');
          };
        })(this),
        isMinimum: (function(_this) {
          return function() {
            return $('.gotoBack').trigger('click');
          };
        })(this)
      });
      return this.preloader = new Preloader({
        imageLoaded: function(index, total) {
          var percent, progressLineRight;
          percent = Math.round(index / total * 100);
          progressLineRight = "" + (100 - percent) + "%";
          $('#splashScreen .progressLine').css({
            right: progressLineRight
          });
          return $('#splashScreen .informer').text("" + percent + "%");
        },
        complete: (function(_this) {
          return function(options) {
            _this.menu.initData(_this.navigation.pages);
            _this.hideSplash();
            return _this.article.show(options.page, options.content, false, 'forward', function() {
              setTimeout(function() {
                _this.showNavigation();
                if (_this.navigation.isLast(options.page)) {
                  return $('.gotoNext').hide();
                }
              }, 1000);
              return _this.events();
            });
          };
        })(this)
      });
    };

    Application.prototype.start = function() {
      this.initShare();
      this.initGA();
      return this.navigation.init((function(_this) {
        return function(page, content) {
          return _this.preloader.init(_this.currentMedia, {
            page: page,
            content: content
          });
        };
      })(this));
    };

    Application.prototype.popup = function(alias) {
      var html;
      this.hideNavigation();
      this.menu.hideMenu();
      this.menu.disable();
      $('.tooltipsLayer').fadeOut('slow');
      return html = this.navigation.loadHtml(alias, (function(_this) {
        return function(html) {
          var newArticle, planes;
          newArticle = $('<article />').addClass('new popup');
          newArticle.attr('id', alias).html(html);
          $(_this.article.article).after(newArticle);
          _this.popupAnimation = new window.animationTypes.popup(_this.article.article, newArticle, {});
          planes = window.Animation.getPlanes(newArticle);
          window.Animation.prepare(planes, false);
          return _this.popupAnimation.forward().run(function() {
            window.Animation.showInfoBlocks(planes.right);
            return $('.popupClose').fadeIn('slow');
          });
        };
      })(this));
    };

    Application.prototype.popupClose = function(callback) {
      if (callback == null) {
        callback = null;
      }
      this.menu.hideMenu();
      $('.popupClose').fadeOut('slow');
      return this.popupAnimation.back().run((function(_this) {
        return function() {
          _this.showNavigation();
          _this.menu.enable();
          $('.tooltipsLayer').fadeIn('slow');
          _this.popupAnimation = null;
          if (callback) {
            return callback();
          }
        };
      })(this));
    };

    Application.prototype.initShare = function() {
      var blockMenuRight;
      blockMenuRight = $("#share-block");
      return $("#share-menu").click((function(_this) {
        return function() {
          if (blockMenuRight.is(':animated')) {
            return;
          }
          if (!blockMenuRight.hasClass("active-menu")) {
            blockMenuRight.addClass("active-menu");
            return blockMenuRight.animate({
              width: "318"
            }, function() {
              _this.shareFlag = true;
            });
          } else {
            return blockMenuRight.animate({
              width: "0"
            }, function() {
              blockMenuRight.removeClass("active-menu");
            });
          }
        };
      })(this));
    };

    Application.prototype.initGA = function() {
      var gAnalytics;
      gAnalytics = {
        event: function() {
          var data;
          data = void 0;
          data = $(this).data();
          ga("send", "event", "button", "click", data.event);
        }
      };
      return $(".ga-btn").on("click", gAnalytics.event);
    };

    Application.prototype.initSplash = function() {
      $('#splashScreen').css({
        width: window.innerWidth,
        height: window.innerHeight
      });
      $('#splashScreen .progressLine').css('right', '100%');
      return $('#splashScreen .informer').text('');
    };

    Application.prototype.showSplash = function(callback) {
      if (callback == null) {
        callback = null;
      }
      $('#splashScreen .progressLine').css('right', '100%');
      $('#splashScreen .informer').text('');
      return $('#splashScreen').show().css({
        width: window.innerWidth,
        height: window.innerHeight
      }).animate({
        opacity: 1
      }, {
        duration: 1000,
        complete: function() {
          if (callback) {
            return callback();
          }
        }
      });
    };

    Application.prototype.hideSplash = function(callback) {
      if (callback == null) {
        callback = null;
      }
      $('.header').fadeIn('slow');
      return $('#splashScreen').show().css({
        opacity: 1
      }).animate({
        opacity: 0
      }, {
        duration: 1000,
        complete: (function(_this) {
          return function() {
            $('#splashScreen').hide();
            $(document).trigger('hideSplash');
            if (!_this.firstLoad) {
              $(window).trigger('resize');
            }
            _this.firstLoad = false;
            if (callback) {
              return callback();
            }
          };
        })(this)
      });
    };

    Application.prototype.goto = function(alias) {
      var page;
      if (window.Animation.isAnimate) {
        return;
      }
      page = this.navigation.getPageByAlias(alias);
      this.menu.hideMenu();
      return this.navigation.goto(page.index, (function(_this) {
        return function(page, html) {
          if (_this.navigation.isLast(page)) {
            _this.hideArrow($('.gotoNext'));
          } else {
            _this.showArrow($('.gotoNext'));
          }
          return _this.article.show(page, html, true, 'forward');
        };
      })(this));
    };

    Application.prototype.next = function() {
      this.menu.hideMenu();
      return this.navigation.next((function(_this) {
        return function(page, html) {
          if (window.Animation.isAnimate) {
            return;
          }
          if (_this.navigation.isLast(page)) {
            _this.hideArrow($('.gotoNext'));
          } else {
            _this.showArrow($('.gotoNext'));
          }
          if (page) {
            return _this.article.show(page, html, true, 'forward');
          }
        };
      })(this));
    };

    Application.prototype.back = function() {
      this.menu.hideMenu();
      if (this.popupAnimation) {
        this.popupAnimation.back().run();
      }
      return this.navigation.previous((function(_this) {
        return function(page, html) {
          if (window.Animation.isAnimate) {
            return;
          }
          if (_this.navigation.isLast(page) && _this.navigation.current !== 0) {
            _this.hideArrow($('.gotoNext'));
          } else {
            _this.showArrow($('.gotoNext'));
          }
          if (page) {
            return _this.article.show(page, html, true, 'back');
          } else {
            return _this.showFade(function() {
              return window.location.href = '../';
            });
          }
        };
      })(this));
    };

    Application.prototype.events = function() {
      $(document).on('click', '.gotoNext', (function(_this) {
        return function(event) {
          event.preventDefault();
          if (_this.popupAnimation) {
            return _this.popupClose(function() {
              return _this.next();
            });
          } else {
            return _this.next();
          }
        };
      })(this));
      $(document).on('click', '.gotoBack', (function(_this) {
        return function(event) {
          event.preventDefault();
          if (_this.popupAnimation) {
            return _this.popupClose(function() {
              return _this.back();
            });
          } else {
            return _this.back();
          }
        };
      })(this));
      $(document).on('click', '.popupClose', (function(_this) {
        return function(event) {
          event.preventDefault();
          return _this.popupClose();
        };
      })(this));
      $(document).on('keydown', (function(_this) {
        return function(event) {
          _this.menu.hideMenu();
          switch (event.keyCode) {
            case 39:
              $('.gotoNext').trigger('click');
              event.preventDefault();
              break;
            case 37:
              $('.gotoBack').trigger('click');
              event.preventDefault();
              break;
          }
        };
      })(this));
      return $(window).on('resize', (function(_this) {
        return function() {
          return _this.resize();
        };
      })(this));
    };

    Application.prototype.resize = function() {
      this.previousMedia = this.currentMedia;
      this.initMedia();
      if (this.popupAnimation) {
        this.popupAnimation.resize();
      }
      if (this.previousMedia !== this.currentMedia) {
        if (this.preloader.preloaded[this.currentMedia]) {
          return;
        }
        return this.navigation.goto(this.navigation.current, (function(_this) {
          return function(page, content) {
            return _this.showSplash(function() {
              _this.preloader.options.complete = function() {
                return _this.hideSplash();
              };
              return _this.preloader.init(_this.currentMedia, {
                page: page,
                content: content
              });
            });
          };
        })(this));
      }
    };

    Application.prototype.showNavigation = function() {
      var navigation;
      navigation = $('footer .footerButtons');
      return navigation.css('top', '100px').show().animate({
        top: -75,
        opacity: 1
      }, {
        queue: false,
        duration: 500,
        easing: 'easeOutBack'
      });
    };

    Application.prototype.hideNavigation = function() {
      var navigation;
      navigation = $('footer .footerButtons');
      return navigation.show().animate({
        top: 100,
        opacity: 0
      }, {
        queue: false,
        duration: 500,
        easing: 'easeOutBack'
      });
    };

    Application.prototype.showFade = function(callback) {
      var fade;
      fade = $('<div />').hide().addClass('fadeSplash');
      $('body').append(fade);
      return fade.show().css({
        opacity: 0,
        width: window.innerWidth,
        height: window.innerHeight
      }).animate({
        opacity: 1
      }, {
        duration: 500,
        complete: function() {
          if (callback) {
            return callback();
          }
        }
      });
    };

    Application.prototype.showArrow = function(arrow) {
      if ($(arrow).is(':hidden')) {
        return arrow.clearQueue().show().animate({
          top: -15,
          opacity: 1
        }, {
          duration: 500,
          easing: 'easeOutBack'
        });
      }
    };

    Application.prototype.hideArrow = function(arrow) {
      if ($(arrow).is(':visible')) {
        return arrow.clearQueue().animate({
          top: -100,
          opacity: 0
        }, {
          duration: 500,
          easing: 'easeInBack',
          complete: function() {
            return $(arrow).hide();
          }
        });
      }
    };

    return Application;

  })();

  $(function() {
    window.app = new Application();
    return window.app.start();
  });

}).call(this);

//# sourceMappingURL=main.map
