// Generated by CoffeeScript 1.7.1
(function() {
  window.Menu = (function() {
    function Menu() {
      this.wrapper = null;
      this.container = null;
      this.isVisible = false;
      this.initialized = false;
      this._init();
      this._events();
    }

    Menu.prototype._init = function() {
      this.wrapper = $('<div />').addClass('mainMenu').hide();
      this.container = $('<div />').addClass('mainMenuContainer').appendTo(this.wrapper);
      this.toggle = $('<a />').addClass('mainMenuToggle');
      this.toggleIcon = $('<i />').addClass('mainMenuIcon').appendTo(this.toggle);
      this.list = $('<ul />').appendTo(this.container);
      $('body').append(this.wrapper);
      return $('body').append(this.toggle);
    };

    Menu.prototype.initData = function(pages) {
      var a, li, page, _i, _len, _results;
      if (this.initialized) {
        return;
      }
      this.initialized = true;
      _results = [];
      for (_i = 0, _len = pages.length; _i < _len; _i++) {
        page = pages[_i];
        if (page.inMenu) {
          li = $('<li />').appendTo(this.list);
          _results.push(a = $('<a />').text(page.title).attr('href', "#" + page.alias).appendTo(li));
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    };

    Menu.prototype._events = function() {
      this.toggle.on('click', (function(_this) {
        return function(event) {
          event.preventDefault();
          if (_this.isVisible) {
            return _this.hideMenu();
          } else {
            return _this.showMenu();
          }
        };
      })(this));
      $(document).on('click', '.mainMenu a', (function(_this) {
        return function(event) {
          var href;
          event.preventDefault();
          event.stopPropagation();
          href = $(event.target).attr('href').replace('#', '');
          window.app.goto(href);
          if (window.app.popupAnimation) {
            window.app.popupAnimation.back().run();
          }
          return _this.hideMenu();
        };
      })(this));
      $('html').on('click', (function(_this) {
        return function(event) {
          if ($(event.target).hasClass('mainMenuIcon')) {
            return;
          }
          if ($(event.target).closest('.mainMenu').length === 0 && _this.isVisible) {
            return _this.hideMenu();
          }
        };
      })(this));
      $(window).on('resize', (function(_this) {
        return function(event) {
          return _this.resize();
        };
      })(this));
      return this.resize();
    };

    Menu.prototype.resize = function() {
      if (window.Animation.article) {
        return $(this.wrapper).height(window.Animation.article.height());
      } else {
        return $(this.wrapper).height(window.innerHeight);
      }
    };

    Menu.prototype.showMenu = function() {
      if (this.isVisible) {
        return;
      }
      this.enable();
      this.isVisible = true;
      this.moveArticle('forward');
      this.wrapper.clearQueue().css({
        left: -this.wrapper.width()
      }).show().animate({
        left: 0
      }, {
        duration: 500,
        queue: false
      });
      this.toggle.addClass('opened').animate({
        left: this.wrapper.width() - 60
      }, {
        queue: false
      });
      return window.Transitions.rotate(this.toggle, 90);
    };

    Menu.prototype.hideMenu = function() {
      if (this.isVisible === false) {
        return;
      }
      this.isVisible = false;
      this.moveArticle('back');
      this.wrapper.clearQueue().animate({
        left: -this.wrapper.width()
      }, {
        duration: 1000,
        complete: (function(_this) {
          return function() {
            return _this.wrapper.hide();
          };
        })(this)
      });
      this.toggle.removeClass('opened').animate({
        left: 30
      }, {
        duration: 500,
        queue: false
      });
      return window.Transitions.rotate(this.toggle, 0);
    };

    Menu.prototype.disable = function() {
      return this.toggle.fadeOut('slow');
    };

    Menu.prototype.enable = function() {
      return this.toggle.fadeIn('slow');
    };

    Menu.prototype.moveArticle = function(direction) {
      var article;
      if (direction == null) {
        direction = 'forward';
      }
      article = $('article');
      this.animation = new window.animationTypes.menu(article, article, {});
      return this.animation[direction]().run();
    };

    return Menu;

  })();

}).call(this);

//# sourceMappingURL=menu.map
