// Generated by CoffeeScript 1.7.1
(function() {
  window.Preloader = (function() {
    Preloader.prototype.images = [];

    Preloader.prototype.allImages = [];

    Preloader.prototype.options = {
      imageLoaded: null,
      complete: null
    };

    Preloader.prototype.preloaded = {
      normal: false,
      big: false
    };

    function Preloader(options) {
      $.extend(this.options, options);
      $(window).on('resize', (function(_this) {
        return function(event) {
          return _this._resize();
        };
      })(this));
    }

    Preloader.prototype.setMedia = function(media) {
      this.media = media;
      this.notMedia = this.media === 'normal' ? '/big/' : '/normal/';
      return this;
    };

    Preloader.prototype.init = function(media, options) {
      this.setMedia(media);
      this.completeOptions = options;
      this.prepare();
      return this.loadImages();
    };

    Preloader.prototype._resize = function() {
      return $('#splashScreen').css({
        width: window.innerWidth,
        height: window.innerHeight
      });
    };

    Preloader.prototype.prepare = function() {
      var baseURLarr, cssPile, csshref, i, images, img, imgUrls, j, k, sheets, thisSheetRules, _i, _len, _results;
      k = 0;
      sheets = document.styleSheets;
      i = 0;
      _results = [];
      while (i < sheets.length) {
        cssPile = "";
        csshref = (sheets[i].href ? sheets[i].href : "window.location.href");
        baseURLarr = csshref.split("/");
        baseURLarr.pop();
        this.baseURL = baseURLarr.join("/");
        if (this.baseURL !== "") {
          this.baseURL += "/";
        }
        if (document.styleSheets[i].cssRules) {
          thisSheetRules = document.styleSheets[i].cssRules;
          j = 0;
          while (j < thisSheetRules.length) {
            cssPile += thisSheetRules[j].cssText;
            j++;
          }
        } else {
          cssPile += document.styleSheets[i].cssText;
        }
        imgUrls = cssPile.match(/[^\(]+\.(gif|jpg|jpeg|png)/g);
        if ((imgUrls != null) && imgUrls.length > 0 && imgUrls !== "") {
          this.images = [];
          images = jQuery.unique(jQuery.makeArray(imgUrls));
          for (_i = 0, _len = images.length; _i < _len; _i++) {
            img = images[_i];
            if (img.indexOf(this.notMedia) === -1) {
              this.images.push(img);
            }
          }
        }
        _results.push(i++);
      }
      return _results;
    };

    Preloader.prototype.loadImages = function() {
      var startIndex;
      if (this.preloaded[this.media]) {
        if (this.options.complete) {
          this.options.complete(this.completeOptions);
        }
        return;
      }
      startIndex = 0;
      return this.loadImage(0, (function(_this) {
        return function() {
          _this.preloaded[_this.media] = true;
          if (_this.options.complete) {
            return _this.options.complete(_this.completeOptions);
          }
        };
      })(this));
    };

    Preloader.prototype.loadImage = function(index, callback) {
      var image, src;
      image = this.images[index];
      this.allImages[index] = new Image();
      src = image[0] === "/" || image.match("http://") || image.match("https://") ? image : this.baseURL + image;
      src = src.replace('"', "");
      return $(this.allImages[index]).attr("src", src).load((function(_this) {
        return function() {
          if (_this.options.imageLoaded) {
            _this.options.imageLoaded(index, _this.images.length);
          }
          if (_this.images[index + 1]) {
            return _this.loadImage(index + 1, callback);
          } else {
            return callback();
          }
        };
      })(this));
    };

    return Preloader;

  })();

}).call(this);

//# sourceMappingURL=preloader.map
