// Generated by CoffeeScript 1.7.1
(function() {
  window.Transitions = (function() {
    function Transitions() {}

    Transitions.rotate = function(object, angle) {
      return $(object).css({
        '-webkit-transform': 'rotate(' + angle + 'deg)',
        '-moz-transform': 'rotate(' + angle + 'deg)',
        '-ms-transform': 'rotate(' + angle + 'deg)',
        '-o-transform': 'rotate(' + angle + 'deg)',
        'transform': 'rotate(' + angle + 'deg)',
        'zoom': 1
      });
    };

    return Transitions;

  })();

}).call(this);

//# sourceMappingURL=transitions.map
