// Generated by CoffeeScript 1.7.1
(function() {
  var FamilyPage;

  FamilyPage = (function() {
    FamilyPage.prototype.currentMedia = null;

    function FamilyPage() {
      this._init();
    }

    FamilyPage.prototype._init = function() {
      this.carsContainer = $('article#family .carsContainer');
      this.car = $('article#family .familyCar');
      window.Animation.addPageCallback((function(_this) {
        return function() {
          return _this.pageStart();
        };
      })(this));
      window.Animation.addResizeCallback((function(_this) {
        return function() {
          return _this._resize();
        };
      })(this));
      return this.image = new Image();
    };

    FamilyPage.prototype.pageStart = function() {
      return this._resize();
    };

    FamilyPage.prototype.getWidth = function() {
      var dummy, dummyWidth, offset, planes, width;
      planes = window.Animation.getPlanes($('article#family'));
      dummy = $('article#family .carDummy');
      dummyWidth = $(dummy).width();
      offset = $('article#family').width() - parseInt($('.planeWrapper', planes.right).css('min-width')) - 50;
      width = dummyWidth + offset;
      return width;
    };

    FamilyPage.prototype._resize = function() {
      var height, picHeight, planes, width;
      planes = window.Animation.getPlanes($('article#family'));
      width = this.getWidth();
      this.carsContainer.css({
        width: width * 0.9,
        height: $('article#family').height()
      });
      height = $('article#family').height();
      this.car.css({
        width: '100%',
        height: height
      });
      picHeight = this.getHeight();
      return this.resizeLinks(picHeight);
    };

    FamilyPage.prototype.resizeLinks = function(height) {
      var linkCount, linkHeight, linkMargin, links, marginTop;
      links = $('.links', this.car);
      marginTop = ($('article#family').height() - height) / 2;
      links.css({
        height: height,
        marginTop: marginTop
      });
      linkCount = $('a', links).length;
      linkHeight = height / linkCount;
      linkMargin = linkHeight * Math.tan(window.Animation.rotateAngleRad);
      return $('a', links).each((function(_this) {
        return function(index, link) {
          var margin;
          margin = (linkCount - index - 1) * linkMargin * 0.9;
          return $(link).css({
            height: linkHeight,
            width: linkHeight * 1.25,
            marginLeft: margin
          });
        };
      })(this));
    };

    FamilyPage.prototype.getHeight = function() {
      var height, src;
      this.previousMedia = this.currentMedia;
      this._detectCurrentMedia();
      if (this.previousMedia !== this.currentMedia) {
        src = this.car.css('background-image').replace('url(', '').replace(/"|\)/g, '');
        console.debug(src);
        this.image.src = src;
        this.proportion = this.image.height / this.image.width;
      }
      height = this.car.width() * this.proportion;
      return height;
    };

    FamilyPage.prototype._detectCurrentMedia = function() {
      if (parseInt($('body').css('z-index')) === 1) {
        return this.currentMedia = 'normal';
      } else {
        return this.currentMedia = 'big';
      }
    };

    return FamilyPage;

  })();

  $(function() {
    return window.family = new FamilyPage();
  });

}).call(this);

//# sourceMappingURL=family.map
