// Generated by CoffeeScript 1.7.1
(function() {
  var PropertiesPage;

  PropertiesPage = (function() {
    function PropertiesPage() {
      this.links = $('.carTitles a');
      this.events();
    }

    PropertiesPage.prototype.events = function() {
      return this.links.on('click', (function(_this) {
        return function(event) {
          var link, target;
          event.preventDefault();
          link = $(event.currentTarget);
          target = link.attr('href').replace('#', '');
          return _this.show(target, link);
        };
      })(this));
    };

    PropertiesPage.prototype.show = function(target, object) {
      this.links.removeClass('active');
      $(object).addClass('active');
      return $(".infoBlock .right:not(\#" + target + ")").fadeOut('slow', (function(_this) {
        return function() {
          $("article#properties .infoBlock").removeClass('gt gt_pro').addClass(target);
          return $("\#" + target).fadeIn('slow');
        };
      })(this));
    };

    return PropertiesPage;

  })();

  $(function() {
    return window.properties = new PropertiesPage();
  });

}).call(this);

//# sourceMappingURL=properties.map
