// Generated by CoffeeScript 1.7.1
(function() {
  var TechnologyPage;

  TechnologyPage = (function() {
    function TechnologyPage() {
      this.car = $('.technologyCar');
      this.pageStart();
    }

    TechnologyPage.prototype.pageStart = function() {
      var infoBlock, infoWidth, right, width;
      this.car.show().animate({
        top: 0
      }, {
        duration: 1000,
        easing: 'easeOutQuad'
      });
      infoBlock = $('article#technology .infoBlock');
      infoBlock.css('opacity', 1);
      $('h2, .description', infoBlock).hide();
      width = $('.titleLine', infoBlock).width();
      $('.titleLine', infoBlock).css({
        width: 0,
        opacity: 0
      });
      right = parseInt($(infoBlock).css('right'));
      infoWidth = parseInt($(infoBlock).css('width'));
      $('h2, .description', infoBlock).show();
      return infoBlock.clearQueue().delay(600).css({
        right: -infoWidth
      }).animate({
        right: right
      }, {
        duration: 300,
        easing: 'easeOutQuad',
        complete: (function(_this) {
          return function() {
            infoBlock.removeClass('custom');
            return $('.titleLine', infoBlock).animate({
              width: width,
              opacity: 1
            }, {
              progress: function(now, fx) {
                var mr;
                mr = width - $(now.elem).width();
                return $('.titleLine', infoBlock).css({
                  marginRight: mr
                });
              },
              duration: 300,
              queue: false
            });
          };
        })(this)
      });
    };

    return TechnologyPage;

  })();

  window.technology = new TechnologyPage();

}).call(this);

//# sourceMappingURL=technology.map
